# This is a basic workflow to help you get started with Actions

name: appcenter.ms

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - name: Flutter action
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.6'
      - run: flutter pub get
      - run: flutter pub get
      #- run: flutter test
      - run: flutter pub run flutter_launcher_icons:main
      - run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml && git commit -m "Bump version" pubspec.yaml
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign
      - name: upload Android artefact to App Center
        uses: joabalea/App-Center-action@v1.0.2
        with:
          command: appcenter distribute stores publish -s Alpha -f build/app/outputs/flutter-apk/app-release.apk -a semack/zxtapeplayer
          token: ${{AC_ANDROID_TOKEN}}