name: appcenter.ms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/cache@v2
        with:
          path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ runner.os }}-gradle-
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'   
      - name: Prepare packages
        run: | 
          flutter pub get
          flutter pub run flutter_launcher_icons:main
      - name: Build Android app
        run: |
          echo "test"
        #  flutter build apk --release --build-number=$BUILD_NUMBER --no-shrink
      - uses: actions/cache@v2
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
           ${{ runner.os }}-pods-
      - name: Build iOS app
        run: | 
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y app.zip Payload/Runner.app
          mv app.zip app.ipa
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install AppCenter CLI
        run: |
          npm install -g appcenter-cli 
      - name: Upload AppCenter artifacts
        run: | 
          appcenter login --token ${{secrets.APPCENTER_TOKEN}}
          pwd
          ls
          appcenter distribute release -g Testers  -a semack-owd8/ZxTapePlayer.iOS -f app.ipa
        # appcenter distribute release -g Testers  -a semack-owd8/ZxTapePlayer.Android -f build/app/outputs/flutter-apk/app-release.apk
          
  
