# This is a basic workflow to help you get started with Actions

name: appcenter.ms

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter action
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.6'    
      - name: Flutter pub get && run
        run: | 
          flutter pub get
          flutter pub run flutter_launcher_icons:main
      - name: Build Android .apk
        run: flutter build apk
#      - name: Build iOS .ipk
#        run: flutter build ios --release --no-codesign
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install appcenter-cli and login to it
        run: npm install -g appcenter-cli && appcenter login --token ${{secrets.APPCENTER_TOKEN}}
      - name: Upload artifacts
        run: appcenter distribute release -g Testers  -a semack-owd8/ZxTapePlayer.Android -f build/app/outputs/flutter-apk/app-release.apk
  #     run: appcenter distribute release -g Testers  -a semack-owd8/ZxTapePlayer.iOS -f app-release.ipk
  
