# This is a basic workflow to help you get started with Actions

name: fastline-appcenter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare packages
        run: | 
          flutter pub get
          flutter pub run flutter_launcher_icons:main
      - name: Build iOS
        run: flutter build ios --release --no-pub --no-codesign --build-number=$BUILD_NUMBER
     # - name: Build Android
     #   run: flutter build apk --release --no-pub --build-number=$BUILD_NUMBER --no-shrink
      - name: Publish iOS
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'beta'
          subdirectory: 'ios'
          bundle-install-path: 'vendor/bundle'
     # - name: Publish Android
     #   uses: maierj/fastlane-action@v2.0.1
     #   with:
     #     lane: 'beta'
     #     subdirectory: 'android'
     #     bundle-install-path: 'vendor/bundle'    

