# This is a basic workflow to help you get started with Actions

name: fastline-appcenter-ios

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.6'    
      - name: Prepare packages
        run: | 
          flutter pub get
          flutter pub run flutter_launcher_icons:main
      - name: Build iOS app
        run: | 
          flutter build ios --release --no-codesign --build-number=$BUILD_NUMBER
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
          cd ../../../
      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.0.1
        with:
        # The lane that should be executed.
          lane: 'ios_appcenter'
          # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
          subdirectory: 'ios'
      

